export const menus = {
  home: "/",
  verification: "/verification",
  jobs: "/jobs",
  premium: "/premium",
  postJob: "/post-jobs",
  myWork: "/my-works",
  acceptedTask: "/my-works/accepted-task",
  myJobs: "/my-jobs",
  notification: "/notification",
  deposit: "/deposit",
  shareAndEarn: "/share",
  "deposit-history": "/history/deposit-history",
  "withdraw-history": "/history/withdraw-history",
  "add-new-ads": "/add-new-ads",
  history: "/history",
  ticket: "/ticket",
  topJobPoster: "/top-job-poster",
  topReffer: "/top-reffer",
  topWorkers: "/top-workers",
  bestUsers: "/top-users",
  userProfile: "/user-profile",
  wallet: "/wallet",
  playandearn:"/play-and-earn",
  "live-support": "/live-support",
  "join-telegram": "/join-telegram",
};
